services:
  # Backend Service
  - type: web
    name: telegram-auto-board-backend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-auto-board-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: API_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true

  # Frontend Service
  - type: web
    name: telegram-auto-board-frontend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://telegram-auto-board-backend.onrender.com/api
      - key: NODE_ENV
        value: production

databases:
  - name: telegram-auto-board-db
    region: frankfurt
    plan: free
    databaseName: auto_board
    user: auto_board_user