services:
  # Backend Service
  - type: web
    name: telegram-auto-board-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-auto-board-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: WEBAPP_URL
        value: https://telegram-auto-board-frontend.vercel.app
      - key: API_PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: telegram-auto-board-db
    region: oregon
    plan: free
    databaseName: auto_board
    user: auto_board_user